### ISSUE TITLE
Verify that all of the Python code examples are Python3 "friendly"

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-sdk-api-specification#12]
Initially, the Python code demonstrating use of Senzing was written for Python 2.7.   We've now deprecated the use of Python 2.7 in favor of Python 3.6+.  

We should verify that all of our python code (in the Jupyter notebooks) should use Python3 idiom.

**Comment by docktermj** [comment]
Things to consider:

1. https://docs.python.org/3/howto/pyporting.html

**Comment by docktermj** [comment]
Actually this may be as simple as:

1. Run Jupyter Notebooks using https://github.com/Senzing/docker-compose-demo
1. Verify that a `Python3` kernel is running in each notebook
1. Verify that all Jupyter notebooks run without syntax error

**Comment by jeffadair** [comment]
I checked it as @docktermj suggested above. It was already running with python 3.7 so no changes were needed in that respect. So I checked the python code for pep 8 style and made some minor fixes so when customers copy/paste our code they get code with good style.
