### ISSUE TITLE
Improve documentation for G2Engine

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzing-sdk-api-specification#34]
The use of flags isn't clearly documented.   Here are some areas that can be improved:

1. https://docs.senzing.com/python/3/g2engine/#addrecordwithinfo
    1. Remove

        ```console
        g2_engine_flags: (int [optional] ) Control flags for specifying what data about the entity to retrieve
        ```

1. https://docs.senzing.com/python/3/g2engine/#reevaluaterecord
    1. Remove

        ```console
        g2_engine_flags: (int [optional]) Control flags for outputting entities
        ```
1. https://docs.senzing.com/python/3/g2engine/#flags
    1. This code should show using flags in `g2_engine.getEntityByEntityID()` not `g2_engine.addRecordWithInfo()`

**Comment by glennjdea** [comment]
This clarification in the docs is much appreciated.  Can I suggest that clarifying the g2_engine_flags in the docs and not in the source might still cause confusion.   In [addRecordWithInfo ](https://github.com/Senzing/g2-sdk-python/blob/main/src/senzing/G2Engine.py#L560) it's described as  "flags: reserved for future use", which I guess is ok.  In [reevaluateRecord](https://github.com/Senzing/g2-sdk-python/blob/main/src/senzing/G2Engine.py#L727) it's "flags: Bitwise control flags", which could still cause confusion.  I guess my point is that ideally the comments in the source should at least not contradict the docs.

**Comment by SamMacy** [comment]
Update docs so that FEATURE_SCORES appear with why functions

**Comment by ryanbasile** [comment]
Improved Python API reference https://docs.senzing.com/python/3/
Added G2Engine flag information and examples https://docs.senzing.com/flags/index.html
